my_strong = input(' введите ваше имя: ')
print('количество символов введеного текста: ', len(my_strong))
print('строка в верхнем регистре:', my_strong.upper())
print('строка в нижнем регистре:', my_strong.lower())
print('удалить все пробелы:', my_strong.replace(' ' , ''))
print('первый символ строки:', my_strong[0])
print('последний символ строки:', my_strong[-1])